services:
  nest-api:
    container_name: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3091:${API_PORT}'
    env_file:
      - .env
  postgres:
    image: postgres:13
    restart: always
    container_name: postgres_text_analyzer
    hostname: ${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
volumes:
  postgresql_data:
    driver: local